"""
Basic Config items.
"""

from pathlib import Path

BASE_DATE_FORMAT = "%y/%m/%d"

HINODE_MOVIES_FILENAME = "*mp4"
HINODE_MOVIES_DATES_SKIP = ()
HINODE_MOVIES_FREQUENCY = None
HINODE_MOVIES_PATH = None
IRIS_MOVIES_DATES_SKIP = ()
IRIS_MOVIES_FILENAME = "*mp4"
IRIS_MOVIES_FREQUENCY = 1
IRIS_MOVIES_PATH = Path("/irisa/mod/podmovie/modvideos/")
SDO_MOVIES_DATES_SKIP = ()
SDO_MOVIES_FILENAME = "*mov.mp4"
SDO_MOVIES_FREQUENCY = 10
SDO_MOVIES_PATH = Path("/viz2/media/SunInTime/")

REQUIRED_PROGRAMS = ("vlc",)

PATHS = (IRIS_MOVIES_PATH, SDO_MOVIES_PATH, HINODE_MOVIES_PATH)
SAMPLE_FREQUENCY = (IRIS_MOVIES_FREQUENCY, SDO_MOVIES_FREQUENCY, HINODE_MOVIES_FREQUENCY)
SKIP_DATES = (IRIS_MOVIES_DATES_SKIP, SDO_MOVIES_DATES_SKIP, HINODE_MOVIES_DATES_SKIP)
FILENAMES = (IRIS_MOVIES_FILENAME, SDO_MOVIES_FILENAME, HINODE_MOVIES_FILENAME)
